workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never

stages:
  - build

default:
  before_script: |
    echo "before script executing..."

    #######################
    ## colored execution ##
    #######################

    exec() {
       # dark green + $ + command line + grey
       echo -e "\e[0;32m\$ $@\e[0;37m"
       $@
       # save the result
       res=$?
       # back to normal output
       echo -e -n "\e[0m"
       # make sure we translate the exit code
       return $res
    }

    # Enable generic CI for building with Anod

    cmd="generic_anod_ci"

    # generic anod ci requires --continuous-builder-mode when not run in a
    # MR context
    if [[ $CI_PIPELINE_SOURCE != "merge_request_event" ]]; then
      cmd="$cmd --continuous-builder-mode"
    fi

    exec eval $cmd
    echo "sourcing the generic CI environment"
    . /tmp/ci_env.sh

    exec anod vcs --list

########
# JOBS #
########

build_and_test:
  services:
    - image:e3
    - cpu:2
  stage: build
  interruptible: true
  parallel:
    matrix:
      - PYTHON: ["3.9", "3.10", "3.11", "3.12"]
  script:
    - anod test  --latest gnatcoll-bindings -Qpython=$PYTHON
    - testsuite_reports
  artifacts:
    reports:
      junit: xunit-*.xml
