#!/usr/bin/env python
from __future__ import annotations
import sys
import os

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(os.path.dirname(ROOT_DIR)))

from gprproject.testsuite import LibTestsuite

class ZstdTestsuite(LibTestsuite):
    @property
    def default_withed_projects(self) -> list[str]:
        return ["gnatcoll_zstd"]

if __name__ == '__main__':
    ZstdTestsuite.main(os.path.dirname(__file__))
